# Generated by Django 5.2.2 on 2025-06-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='meal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mealnamesuggestion'),
        ),
    ]
