# Generated by Django 5.2.2 on 2025-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_mealitem_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='meal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='MealNameSuggestion',
        ),
    ]
